name: youtube_downloader
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  filepicker_windows: ^2.1.4
  flutter:
    sdk: flutter
  flutter_file_dialog: ^3.0.2
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  http: ^1.3.0
  youtube_explode_dart: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
